/* Generated by the Nim Compiler v1.6.12 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var objectID_687866018 = [0];
/// <reference path="./typings/game/constants.d.ts" />
/// <reference path="./typings/game/index.d.ts" />
/// <reference path="./typings/game/path-finder.d.ts" />
/// <reference path="./typings/game/utils.d.ts" />
/// <reference path="./typings/game/visual.d.ts" />

import * as gameUtil from 'game/utils';
import * as gameVisual from 'game/visual';
import * as gamePathFinder from 'game/path-finder';
// NB. not using gameConstants, can just copy them to nim
// not sure what this arena type is but it's not in typings
// import { } from 'arena';


function mainLoop() {
    var currentTick_486539270 = gameUtil.getTicks();
    console.log(("Current tick: "), (currentTick_486539270));

  
}
export const loop = mainLoop;

