image: docker:git

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CONTAINER_REGISTRY: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_BUILDKIT: 1
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

services:
  - docker:dind

stages:
  - build
  # - release

nim-test:
  image: nimlang/nim
  stage: build
  script:
    - nim c -r tests/*
