/* Generated by the Nim Compiler v1.6.12 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI1040187411 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI33555124 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1006632966 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1006632983 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI1006632970 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI33554437 = {size: 0,kind: 36,base: null,node: null,finalizer: null};
var NTI33554456 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI1006632991 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI1006632978 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI1006632994 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI1006632993 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1006632980 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI486539392 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI33555128 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555130 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555113 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555120 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555122 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555083 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555165 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554439 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554440 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555164 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555112 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
NTI33555164.base = NTI33555112;
NTI33555165.base = NTI33555112;
var NNI33555112 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555164, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554440, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554439, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554439, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555165, name: "up", sons: null}]};
NTI33555112.node = NNI33555112;
var NNI33555083 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555083.node = NNI33555083;
NTI33555112.base = NTI33555083;
var NNI33555122 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555122.node = NNI33555122;
var NNI33555120 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555120.node = NNI33555120;
var NNI33555113 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555113.node = NNI33555113;
NTI33555113.base = NTI33555112;
NTI33555120.base = NTI33555113;
NTI33555122.base = NTI33555120;
var NNI33555130 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555130.node = NNI33555130;
NTI33555130.base = NTI33555113;
var NNI33555128 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555128.node = NNI33555128;
NTI33555128.base = NTI33555113;
var NNI1006632991 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "type", len: 0, typ: NTI33554440, name: "type", sons: null}, 
{kind: 1, offset: "hits", len: 0, typ: NTI33554456, name: "hits", sons: null}]};
NTI1006632991.node = NNI1006632991;
NTI1006632978.base = NTI1006632991;
NTI1006632994.base = NTI1006632978;
var NNI1006632983 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1006632983.node = NNI1006632983;
NTI1006632970.base = NTI1006632983;
var NNI1006632993 = {kind: 2, len: 6, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "body", len: 0, typ: NTI1006632994, name: "body", sons: null}, 
{kind: 1, offset: "fatigue", len: 0, typ: NTI33554437, name: "fatigue", sons: null}, 
{kind: 1, offset: "hits", len: 0, typ: NTI33554456, name: "hits", sons: null}, 
{kind: 1, offset: "hitsMax", len: 0, typ: NTI33554456, name: "hitsMax", sons: null}, 
{kind: 1, offset: "my", len: 0, typ: NTI33554466, name: "my", sons: null}, 
{kind: 1, offset: "store", len: 0, typ: NTI1006632970, name: "store", sons: null}]};
NTI1006632993.node = NNI1006632993;
var NNI1006632966 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "exists", len: 0, typ: NTI33554466, name: "exists", sons: null}, 
{kind: 1, offset: "id", len: 0, typ: NTI33554440, name: "id", sons: null}, 
{kind: 1, offset: "ticksToDecay", len: 0, typ: NTI33554456, name: "ticksToDecay", sons: null}, 
{kind: 1, offset: "x", len: 0, typ: NTI33554456, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI33554456, name: "y", sons: null}]};
NTI1006632966.node = NNI1006632966;
NTI1006632966.base = NTI33555083;
NTI1006632993.base = NTI1006632966;
NTI1006632980.base = NTI1006632993;
NTI486539392.base = NTI1006632980;
var NNI33555124 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555124.node = NNI33555124;
NTI33555124.base = NTI33555113;
NTI1040187411.base = NTI33554440;

function makeNimstrLit(c_33556801) {
      var result = [];
  for (var i = 0; i < c_33556801.length; ++i) {
    result[i] = c_33556801.charCodeAt(i);
  }
  return result;
  

  
}

function toJSStr(s_33556807) {
                    var Temporary5;
            var Temporary7;

  var result_33556808 = null;

    var res_33556842 = newSeq_33556825((s_33556807).length);
    var i_33556843 = 0;
    var j_33556844 = 0;
    Label1: do {
        Label2: while (true) {
        if (!(i_33556843 < (s_33556807).length)) break Label2;
          var c_33556845 = s_33556807[i_33556843];
          if ((c_33556845 < 128)) {
          res_33556842[j_33556844] = String.fromCharCode(c_33556845);
          i_33556843 += 1;
          }
          else {
            var helper_33556857 = newSeq_33556825(0);
            Label3: do {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556858 = c_33556845.toString(16);
                  if ((((code_33556858) == null ? 0 : (code_33556858).length) == 1)) {
                  helper_33556857.push("%0");;
                  }
                  else {
                  helper_33556857.push("%");;
                  }
                  
                  helper_33556857.push(code_33556858);;
                  i_33556843 += 1;
                    if (((s_33556807).length <= i_33556843)) Temporary5 = true; else {                      Temporary5 = (s_33556807[i_33556843] < 128);                    }                  if (Temporary5) {
                  break Label3;
                  }
                  
                  c_33556845 = s_33556807[i_33556843];
                }
            } while (false);
++excHandler;
            Temporary7 = framePtr;
            try {
            res_33556842[j_33556844] = decodeURIComponent(helper_33556857.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            framePtr = Temporary7;
            res_33556842[j_33556844] = helper_33556857.join("");
            lastJSError = prevJSError;
            } finally {
            framePtr = Temporary7;
            }
          }
          
          j_33556844 += 1;
        }
    } while (false);
    if (res_33556842.length < j_33556844) { for (var i = res_33556842.length ; i < j_33556844 ; ++i) res_33556842.push(null); }
               else { res_33556842.length = j_33556844; };
    result_33556808 = res_33556842.join("");

  return result_33556808;

}

function raiseException(e_33556667, ename_33556668) {
    e_33556667.name = ename_33556668;
    if ((excHandler == 0)) {
    unhandledException(e_33556667);
    }
    
    throw e_33556667;

  
}

function mnewString(len_33556893) {
        return new Array(len_33556893);
  

  
}

function addInt(a_33556940, b_33556941) {
        var result = a_33556940 + b_33556941;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_33557189, a_33557190, b_33557191) {
      var Temporary1;

  var result_33557192 = 0;

  BeforeRet: do {
      if (!(a_33557190 <= i_33557189)) Temporary1 = false; else {        Temporary1 = (i_33557189 <= b_33557191);      }    if (Temporary1) {
    result_33557192 = i_33557189;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  } while (false);

  return result_33557192;

}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557140, src_33557141, ti_33557142) {
  var result_33557151 = null;

    switch (ti_33557142.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557131(ti_33557142))) {
      result_33557151 = src_33557141;
      }
      else {
        result_33557151 = [src_33557141[0], src_33557141[1]];
      }
      
      break;
    case 19:
            if (dest_33557140 === null || dest_33557140 === undefined) {
        dest_33557140 = {};
      }
      else {
        for (var key in dest_33557140) { delete dest_33557140[key]; }
      }
      for (var key in src_33557141) { dest_33557140[key] = src_33557141[key]; }
      result_33557151 = dest_33557140;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557142.base == null))) {
      result_33557151 = nimCopy(dest_33557140, src_33557141, ti_33557142.base);
      }
      else {
      if ((ti_33557142.kind == 17)) {
      result_33557151 = (dest_33557140 === null || dest_33557140 === undefined) ? {m_type: ti_33557142} : dest_33557140;
      }
      else {
        result_33557151 = (dest_33557140 === null || dest_33557140 === undefined) ? {} : dest_33557140;
      }
      }
      nimCopyAux(result_33557151, src_33557141, ti_33557142.node);
      break;
    case 24:
    case 4:
    case 27:
    case 16:
            if (src_33557141 === null) {
        result_33557151 = null;
      }
      else {
        if (dest_33557140 === null || dest_33557140 === undefined || dest_33557140.length != src_33557141.length) {
          dest_33557140 = new Array(src_33557141.length);
        }
        result_33557151 = dest_33557140;
        for (var i = 0; i < src_33557141.length; ++i) {
          result_33557151[i] = nimCopy(result_33557151[i], src_33557141[i], ti_33557142.base);
        }
      }
    
      break;
    case 28:
            if (src_33557141 !== null) {
        result_33557151 = src_33557141.slice(0);
      }
    
      break;
    default: 
      result_33557151 = src_33557141;
      break;
    }

  return result_33557151;

}

function chckIndx(i_33557184, a_33557185, b_33557186) {
      var Temporary1;

  var result_33557187 = 0;

  BeforeRet: do {
      if (!(a_33557185 <= i_33557184)) Temporary1 = false; else {        Temporary1 = (i_33557184 <= b_33557186);      }    if (Temporary1) {
    result_33557187 = i_33557184;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557184, a_33557185, b_33557186);
    }
    
  } while (false);

  return result_33557187;

}
var objectID_687866018 = [0];
/// <reference path="./node_modules/@types/screeps-arena/game/constants.d.ts" />
/// <reference path="./node_modules/@types/screeps-arena/game/index.d.ts" />
/// <reference path="./node_modules/@types/screeps-arena/game/path-finder.d.ts" />
/// <reference path="./node_modules/@types/screeps-arena/game/utils.d.ts" />
/// <reference path="./node_modules/@types/screeps-arena/game/visual.d.ts" />

import * as gameUtil from 'game/utils';
import * as gameVisual from 'game/visual';
import * as gamePathFinder from 'game/path-finder';
import * as game from 'game';
import * as arena from 'arena';

import { 
  Creep, Source, StructureContainer, StructureTower, StructureSpawn,
  ConstructionSite
 } from 'game/prototypes';
// import { Flag } from 'arena/prototypes';


function getAllCreeps_1040187394() {
  var result_1040187395 = [];

      return gameUtil.getObjectsByPrototype(Creep);
  

  return result_1040187395;

}

function getAllFlags_1040187396() {
  var result_1040187397 = [];

      return gameUtil.getObjectsByPrototype(Flag);
  

  return result_1040187397;

}

function add_33556419(x_33556420, x_33556420_Idx, y_33556421) {
          if (x_33556420[x_33556420_Idx] === null) { x_33556420[x_33556420_Idx] = []; }
      var off = x_33556420[x_33556420_Idx].length;
      x_33556420[x_33556420_Idx].length += y_33556421.length;
      for (var i = 0; i < y_33556421.length; ++i) {
        x_33556420[x_33556420_Idx][off+i] = y_33556421.charCodeAt(i);
      }
    

  
}

function newSeq_33556825(len_33556827) {
  var result_33556828 = [];

    result_33556828 = new Array(len_33556827); for (var i = 0 ; i < len_33556827 ; ++i) { result_33556828[i] = null; }
  return result_33556828;

}

function unhandledException(e_33556663) {
    var buf_33556664 = [[]];
    if (!(((e_33556663.message).length == 0))) {
    buf_33556664[0].push.apply(buf_33556664[0], makeNimstrLit("Error: unhandled exception: "));;
    buf_33556664[0].push.apply(buf_33556664[0], e_33556663.message);;
    }
    else {
    buf_33556664[0].push.apply(buf_33556664[0], makeNimstrLit("Error: unhandled exception"));;
    }
    
    buf_33556664[0].push.apply(buf_33556664[0], makeNimstrLit(" ["));;
    add_33556419(buf_33556664, 0, e_33556663.name);
    buf_33556664[0].push.apply(buf_33556664[0], makeNimstrLit("]\x0A"));;
    var cbuf_33556665 = toJSStr(buf_33556664[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556665);
  }
  else {
    throw cbuf_33556665;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: makeNimstrLit("over- or underflow"), parent: null, m_type: NTI33555122, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_33556938) {
        if (a_33556938 > 2147483647 || a_33556938 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: makeNimstrLit("value out of range"), parent: null, m_type: NTI33555130, name: null, trace: [], up: null}, "RangeDefect");

  
}

function addChars_251658415(result_251658417, result_251658417_Idx, x_251658418, start_251658419, n_251658420) {
    var old_251658421 = (result_251658417[result_251658417_Idx]).length;
    (result_251658417[result_251658417_Idx].length = chckRange(addInt(old_251658421, n_251658420), 0, 2147483647));
    Label1: do {
      var iHEX60gensym4_251658435 = 0;
      var i_486539439 = 0;
      Label2: do {
          Label3: while (true) {
          if (!(i_486539439 < n_251658420)) break Label3;
            iHEX60gensym4_251658435 = i_486539439;
            result_251658417[result_251658417_Idx][chckIndx(addInt(old_251658421, iHEX60gensym4_251658435), 0, (result_251658417[result_251658417_Idx]).length - 1)] = x_251658418.charCodeAt(chckIndx(addInt(start_251658419, iHEX60gensym4_251658435), 0, (x_251658418).length - 1));
            i_486539439 = addInt(i_486539439, 1);
          }
      } while (false);
    } while (false);

  
}

function addChars_251658411(result_251658413, result_251658413_Idx, x_251658414) {
    addChars_251658415(result_251658413, result_251658413_Idx, x_251658414, 0, ((x_251658414) == null ? 0 : (x_251658414).length));

  
}

function addInt_251658436(result_251658437, result_251658437_Idx, x_251658438) {
    addChars_251658411(result_251658437, result_251658437_Idx, ((x_251658438) + ""));

  
}

function addInt_251658457(result_251658458, result_251658458_Idx, x_251658459) {
    addInt_251658436(result_251658458, result_251658458_Idx, x_251658459);

  
}

function HEX24_352321539(x_352321540) {
  var result_352321541 = [[]];

    addInt_251658457(result_352321541, 0, x_352321540);

  return result_352321541[0];

}

function isFatPointer_33557131(ti_33557132) {
  var result_33557133 = false;

  BeforeRet: do {
    result_33557133 = !((ConstSet1[ti_33557132.base.kind] != undefined));
    break BeforeRet;
  } while (false);

  return result_33557133;

}

function nimCopyAux(dest_33557144, src_33557145, n_33557146) {
    switch (n_33557146.kind) {
    case 0:
      break;
    case 1:
            dest_33557144[n_33557146.offset] = nimCopy(dest_33557144[n_33557146.offset], src_33557145[n_33557146.offset], n_33557146.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557146.sons.length; i++) {
      nimCopyAux(dest_33557144, src_33557145, n_33557146.sons[i]);
    }
    
      break;
    case 3:
            dest_33557144[n_33557146.offset] = nimCopy(dest_33557144[n_33557146.offset], src_33557145[n_33557146.offset], n_33557146.typ);
      for (var i = 0; i < n_33557146.sons.length; ++i) {
        nimCopyAux(dest_33557144, src_33557145, n_33557146.sons[i][1]);
      }
    
      break;
    }

  
}

function raiseIndexError(i_33556754, a_33556755, b_33556756) {
    var Temporary1;

    if ((b_33556756 < a_33556755)) {
    Temporary1 = makeNimstrLit("index out of bounds, the container is empty");
    }
    else {
    Temporary1 = (makeNimstrLit("index ") || []).concat(HEX24_352321539(i_33556754) || [],makeNimstrLit(" not in ") || [],HEX24_352321539(a_33556755) || [],makeNimstrLit(" .. ") || [],HEX24_352321539(b_33556756) || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554439), parent: null, m_type: NTI33555128, name: null, trace: [], up: null}, "IndexDefect");

  
}

function simpleMoveLoop() {
    var currentTick_486539272 = gameUtil.getTicks();
    console.log(("Current tick: "), (currentTick_486539272));
    var creeps_486539304 = getAllCreeps_1040187394();
    console.log(("found creeps: "), ((creeps_486539304).length));
    var flags_486539327 = getAllFlags_1040187396();
    console.log(("found flags: "), ((flags_486539327).length));
    if (((creeps_486539304).length < 1)) {
    raiseException({message: makeNimstrLit("No creeps found"), parent: null, m_type: NTI33555112, name: null, trace: [], up: null}, "Exception");
    }
    
    if (((flags_486539327).length < 1)) {
    raiseException({message: makeNimstrLit("No flags found"), parent: null, m_type: NTI33555112, name: null, trace: [], up: null}, "Exception");
    }
    
    var flag_486539358 = flags_486539327[chckIndx(0, 0, (flags_486539327).length - 1)];
    var creep_486539359 = creeps_486539304[chckIndx(0, 0, (creeps_486539304).length - 1)];
    var res_486539360 = creep_486539359.moveTo(flag_486539358);
    console.log(("moveTo result: "), (res_486539360));

  
}

function newSeq_486539512(len_486539514) {
  var result_486539515 = [];

    result_486539515 = new Array(len_486539514); for (var i = 0 ; i < len_486539514 ; ++i) { result_486539515[i] = null; }
  return result_486539515;

}

function filter_486539506(s_486539508, pred_486539510) {
  var result_486539511 = [];

    result_486539511 = nimCopy(null, newSeq_486539512(0), NTI486539392);
    Label1: do {
      var i_486539528 = 0;
      var colontmp__486539625 = 0;
      colontmp__486539625 = (s_486539508).length;
      var i_486539626 = 0;
      Label2: do {
          Label3: while (true) {
          if (!(i_486539626 < colontmp__486539625)) break Label3;
            i_486539528 = i_486539626;
            if (pred_486539510(s_486539508[chckIndx(i_486539528, 0, (s_486539508).length - 1)])) {
            result_486539511.push(s_486539508[chckIndx(i_486539528, 0, (s_486539508).length - 1)]);;
            }
            
            i_486539626 = addInt(i_486539626, 1);
          }
      } while (false);
    } while (false);

  return result_486539511;

}

function firstAttack() {
    
function HEX3Aanonymous_486539502(c_486539503) {
      var result_486539504 = false;

        result_486539504 = c_486539503.my;

      return result_486539504;

    }
    
function HEX3Aanonymous_486539534(c_486539535) {
      var result_486539536 = false;

        result_486539536 = !(c_486539535.my);

      return result_486539536;

    }

    var currentTick_486539442 = gameUtil.getTicks();
    console.log(("Current tick: "), (currentTick_486539442));
    var creeps_486539461 = getAllCreeps_1040187394();
    console.log(("found creeps: "), ((creeps_486539461).length));
    var myCreeps_486539533 = filter_486539506(creeps_486539461, HEX3Aanonymous_486539502);
    var enemyCreeps_486539543 = filter_486539506(creeps_486539461, HEX3Aanonymous_486539534);
    if (((myCreeps_486539533).length < 1)) {
    raiseException({message: makeNimstrLit("No my creeps found"), parent: null, m_type: NTI33555112, name: null, trace: [], up: null}, "Exception");
    }
    
    if (((enemyCreeps_486539543).length < 1)) {
    raiseException({message: makeNimstrLit("No enemy creeps found"), parent: null, m_type: NTI33555112, name: null, trace: [], up: null}, "Exception");
    }
    
    var myCreep_486539552 = myCreeps_486539533[chckIndx(0, 0, (myCreeps_486539533).length - 1)];
    var enemyCreep_486539553 = enemyCreeps_486539543[chckIndx(0, 0, (enemyCreeps_486539543).length - 1)];
    var attackRes_486539554 = myCreep_486539552.attack(enemyCreep_486539553);
    console.log(("attack result: "), (attackRes_486539554));
    if ((attackRes_486539554 == -9)) {
    var moveRes_486539578 = myCreep_486539552.moveTo(enemyCreep_486539553);
    console.log(("moveTo result: "), (moveRes_486539578));
    }
    

  
}

function sysFatal_218103842(message_218103845) {
    raiseException({message: nimCopy(null, message_218103845, NTI33554439), m_type: NTI33555124, parent: null, name: null, trace: [], up: null}, "AssertionDefect");

  
}

function raiseAssert_218103840(msg_218103841) {
    sysFatal_218103842(msg_218103841);

  
}

function failedAssertImpl_218103864(msg_218103865) {
    raiseAssert_218103840(msg_218103865);

  
}

function creepsBodies() {
    
function HEX3Aanonymous_486539651(c_486539652) {
      var result_486539653 = false;

        result_486539653 = !(c_486539652.my);

      return result_486539653;

    }
    
function HEX3Aanonymous_486539665(c_486539666) {
      var result_486539667 = false;

        result_486539667 = c_486539666.my;

      return result_486539667;

    }
    
function HEX3Aanonymous_486539675(c_486539676) {
      var result_486539677 = false;

        var resultHEX60gensym50_486539679 = false;
        Label1: do {
          var it_486539701 = null;
          var i_486540024 = 0;
          var L_486540025 = (c_486539676.body).length;
          Label2: do {
              Label3: while (true) {
              if (!(i_486540024 < L_486540025)) break Label3;
                it_486539701 = c_486539676.body[chckIndx(i_486540024, 0, (c_486539676.body).length - 1)];
                if ((it_486539701.type == "attack")) {
                resultHEX60gensym50_486539679 = true;
                break Label1;
                }
                
                i_486540024 = addInt(i_486540024, 1);
                if (!(((c_486539676.body).length == L_486540025))) {
                failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                }
                
              }
          } while (false);
        } while (false);
        result_486539677 = resultHEX60gensym50_486539679;

      return result_486539677;

    }
    
function HEX3Aanonymous_486539727(c_486539728) {
      var result_486539729 = false;

        var resultHEX60gensym53_486539731 = false;
        Label1: do {
          var it_486539735 = null;
          var i_486540028 = 0;
          var L_486540029 = (c_486539728.body).length;
          Label2: do {
              Label3: while (true) {
              if (!(i_486540028 < L_486540029)) break Label3;
                it_486539735 = c_486539728.body[chckIndx(i_486540028, 0, (c_486539728.body).length - 1)];
                if ((it_486539735.type == "ranged_attack")) {
                resultHEX60gensym53_486539731 = true;
                break Label1;
                }
                
                i_486540028 = addInt(i_486540028, 1);
                if (!(((c_486539728.body).length == L_486540029))) {
                failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                }
                
              }
          } while (false);
        } while (false);
        result_486539729 = resultHEX60gensym53_486539731;

      return result_486539729;

    }
      
function HEX3Aanonymous_486539743(c_486539744) {
        var result_486539745 = false;

          result_486539745 = c_486539744.my;

        return result_486539745;

      }

    var creeps_486539629 = getAllCreeps_1040187394();
    console.log(("found creeps: "), ((creeps_486539629).length));
    var enemyCreeps_486539660 = filter_486539506(creeps_486539629, HEX3Aanonymous_486539651);
    if (((enemyCreeps_486539660).length < 1)) {
    raiseException({message: makeNimstrLit("No enemy creeps found"), parent: null, m_type: NTI33555112, name: null, trace: [], up: null}, "Exception");
    }
    
    var myCreeps_486539674 = filter_486539506(creeps_486539629, HEX3Aanonymous_486539665);
    var attackCreeps_486539726 = filter_486539506(myCreeps_486539674, HEX3Aanonymous_486539675);
    var rangedCreeps_486539742 = filter_486539506(myCreeps_486539674, HEX3Aanonymous_486539727);
    Label1: do {
      var c_486539762 = null;
      var colontmp__486540013 = null;
      colontmp__486540013 = HEX3Aanonymous_486539743;
      Label2: do {
        var i_486540019 = 0;
        var colontmp__486540020 = 0;
        colontmp__486540020 = (creeps_486539629).length;
        var i_486540021 = 0;
        Label3: do {
            Label4: while (true) {
            if (!(i_486540021 < colontmp__486540020)) break Label4;
              i_486540019 = i_486540021;
              if (colontmp__486540013(creeps_486539629[chckIndx(i_486540019, 0, (creeps_486539629).length - 1)])) {
              c_486539762 = creeps_486539629[chckIndx(i_486540019, 0, (creeps_486539629).length - 1)];
              console.log(("creep: "), (c_486539762.id));
              console.log(("body: "), (c_486539762.body));
              Label5: do {
                var b_486539802 = null;
                var i_486539998 = 0;
                var L_486539999 = (c_486539762.body).length;
                Label6: do {
                    Label7: while (true) {
                    if (!(i_486539998 < L_486539999)) break Label7;
                      b_486539802 = c_486539762.body[chckIndx(i_486539998, 0, (c_486539762.body).length - 1)];
                      console.log(("part: "), (b_486539802.type));
                      console.log(("ATTACK"), ("attack"));
                      i_486539998 = addInt(i_486539998, 1);
                      if (!(((c_486539762.body).length == L_486539999))) {
                      failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                      }
                      
                    }
                } while (false);
              } while (false);
                var resultHEX60gensym74_486539840 = false;
                Label8: do {
                  var it_486539844 = null;
                  var i_486540002 = 0;
                  var L_486540003 = (c_486539762.body).length;
                  Label9: do {
                      Label10: while (true) {
                      if (!(i_486540002 < L_486540003)) break Label10;
                        it_486539844 = c_486539762.body[chckIndx(i_486540002, 0, (c_486539762.body).length - 1)];
                        if ((it_486539844.type == "attack")) {
                        resultHEX60gensym74_486539840 = true;
                        break Label8;
                        }
                        
                        i_486540002 = addInt(i_486540002, 1);
                        if (!(((c_486539762.body).length == L_486540003))) {
                        failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                        }
                        
                      }
                  } while (false);
                } while (false);
              if (resultHEX60gensym74_486539840) {
              console.log(("creep has attack part: "), (c_486539762.id));
              if ((0 < (enemyCreeps_486539660).length)) {
              if ((c_486539762.attack(enemyCreeps_486539660[chckIndx(0, 0, (enemyCreeps_486539660).length - 1)]) == -9)) {
              var _ = c_486539762.moveTo(enemyCreeps_486539660[chckIndx(0, 0, (enemyCreeps_486539660).length - 1)]);
              }
              
              }
              else {
              console.log(("no other creeps to attack"));
              }
              
              }
              else {
                var resultHEX60gensym84_486539885 = false;
                Label11: do {
                  var it_486539889 = null;
                  var i_486540006 = 0;
                  var L_486540007 = (c_486539762.body).length;
                  Label12: do {
                      Label13: while (true) {
                      if (!(i_486540006 < L_486540007)) break Label13;
                        it_486539889 = c_486539762.body[chckIndx(i_486540006, 0, (c_486539762.body).length - 1)];
                        if ((it_486539889.type == "ranged_attack")) {
                        resultHEX60gensym84_486539885 = true;
                        break Label11;
                        }
                        
                        i_486540006 = addInt(i_486540006, 1);
                        if (!(((c_486539762.body).length == L_486540007))) {
                        failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                        }
                        
                      }
                  } while (false);
                } while (false);
              if (resultHEX60gensym84_486539885) {
              console.log(("creep has ranged attack part: "), (c_486539762.id));
              if ((0 < (enemyCreeps_486539660).length)) {
              if ((c_486539762.rangedAttack(enemyCreeps_486539660[chckIndx(0, 0, (enemyCreeps_486539660).length - 1)]) == -9)) {
              var _ = c_486539762.moveTo(enemyCreeps_486539660[chckIndx(0, 0, (enemyCreeps_486539660).length - 1)]);
              }
              
              }
              else {
              console.log(("no other creeps to attack"));
              }
              
              }
              else {
                var resultHEX60gensym94_486539930 = false;
                Label14: do {
                  var it_486539934 = null;
                  var i_486540010 = 0;
                  var L_486540011 = (c_486539762.body).length;
                  Label15: do {
                      Label16: while (true) {
                      if (!(i_486540010 < L_486540011)) break Label16;
                        it_486539934 = c_486539762.body[chckIndx(i_486540010, 0, (c_486539762.body).length - 1)];
                        if ((it_486539934.type == "heal")) {
                        resultHEX60gensym94_486539930 = true;
                        break Label14;
                        }
                        
                        i_486540010 = addInt(i_486540010, 1);
                        if (!(((c_486539762.body).length == L_486540011))) {
                        failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                        }
                        
                      }
                  } while (false);
                } while (false);
              if (resultHEX60gensym94_486539930) {
              console.log(("creep has heal part: "), (c_486539762.id));
              if ((0 < (attackCreeps_486539726).length)) {
              if ((c_486539762.heal(attackCreeps_486539726[chckIndx(0, 0, (attackCreeps_486539726).length - 1)]) == -9)) {
              var _ = c_486539762.moveTo(attackCreeps_486539726[chckIndx(0, 0, (attackCreeps_486539726).length - 1)]);
              }
              
              }
              else {
              if ((0 < (rangedCreeps_486539742).length)) {
              if ((c_486539762.heal(rangedCreeps_486539742[chckIndx(0, 0, (rangedCreeps_486539742).length - 1)]) == -9)) {
              var _ = c_486539762.moveTo(rangedCreeps_486539742[chckIndx(0, 0, (rangedCreeps_486539742).length - 1)]);
              }
              
              }
              else {
              console.log(("no other creeps to heal"));
              }
              }
              }
              else {
              console.log(("creep missing attack or heal part"));
              }
              }}
              }
              
              i_486540021 = addInt(i_486540021, 1);
            }
        } while (false);
      } while (false);
    } while (false);

  
}

function getAllContainers_1040187398() {
  var result_1040187399 = [];

      return gameUtil.getObjectsByPrototype(StructureContainer);
  

  return result_1040187399;

}

function getAllTowers_1040187400() {
  var result_1040187401 = [];

      return gameUtil.getObjectsByPrototype(StructureTower);
  

  return result_1040187401;

}

function storeAndTransfer() {
      
function HEX3Aanonymous_486540073(c_486540074) {
        var result_486540075 = false;

          result_486540075 = c_486540074.my;

        return result_486540075;

      }
    var Temporary5;
    
function HEX3Aanonymous_486540240(c_486540241) {
      var result_486540242 = false;

        result_486540242 = !(c_486540241.my);

      return result_486540242;

    }
    var Temporary6;

    var currentTick_486540032 = gameUtil.getTicks();
    console.log(("Current tick: "), (currentTick_486540032));
    var creeps_486540051 = getAllCreeps_1040187394();
    console.log(("found creeps: "), ((creeps_486540051).length));
    Label1: do {
      var c_486540084 = null;
      var colontmp__486540344 = null;
      colontmp__486540344 = HEX3Aanonymous_486540073;
      Label2: do {
        var i_486540346 = 0;
        var colontmp__486540347 = 0;
        colontmp__486540347 = (creeps_486540051).length;
        var i_486540348 = 0;
        Label3: do {
            Label4: while (true) {
            if (!(i_486540348 < colontmp__486540347)) break Label4;
              i_486540346 = i_486540348;
              if (colontmp__486540344(creeps_486540051[chckIndx(i_486540346, 0, (creeps_486540051).length - 1)])) {
              c_486540084 = creeps_486540051[chckIndx(i_486540346, 0, (creeps_486540051).length - 1)];
              console.log(("creep: "), (c_486540084.id));
              console.log(("body: "), (c_486540084.body));
              if ((c_486540084.store.getUsedCapacity() == 0)) {
              var containers_486540121 = getAllContainers_1040187398();
              console.log(("found containers: "), ((containers_486540121).length));
              if ((0 < (containers_486540121).length)) {
              var container_486540150 = containers_486540121[chckIndx(0, 0, (containers_486540121).length - 1)];
              if ((c_486540084.withdraw(container_486540150, "energy") == -9)) {
              var _ = c_486540084.moveTo(container_486540150);
              }
              
              }
              else {
              console.log(("no containers found"));
              }
              
              }
              else {
                var towers_486540166 = getAllTowers_1040187400();
                console.log(("found towers: "), ((towers_486540166).length));
                if ((0 < (towers_486540166).length)) {
                var tower_486540195 = towers_486540166[chckIndx(0, 0, (towers_486540166).length - 1)];
                if ((c_486540084.transfer(tower_486540195, "energy") == -9)) {
                var _ = c_486540084.moveTo(tower_486540195);
                }
                
                }
                else {
                console.log(("no towers found"));
                }
                
              }
              
              }
              
              i_486540348 = addInt(i_486540348, 1);
            }
        } while (false);
      } while (false);
    } while (false);
    var towers_486540211 = getAllTowers_1040187400();
    console.log(("found towers: "), ((towers_486540211).length));
    if ((0 < (towers_486540211).length)) {
    var tower_486540239 = towers_486540211[chckIndx(0, 0, (towers_486540211).length - 1)];
    var enemyCreeps_486540249 = filter_486539506(creeps_486540051, HEX3Aanonymous_486540240);
    if ((0 < (enemyCreeps_486540249).length)) {
    var enemyCreep_486540256 = enemyCreeps_486540249[chckIndx(0, 0, (enemyCreeps_486540249).length - 1)];
    var res_486540257 = tower_486540239.attack(enemyCreep_486540256);
    Temporary6 = console.log(("tower attack result: "), (res_486540257));
    }
    else {
    Temporary6 = console.log(("no enemy creeps found"));
    }
    
    Temporary5 = Temporary6;
    }
    else {
    Temporary5 = console.log(("no towers found"));
    }
    
    Temporary5;

  
}

function terrainMove() {
            var Temporary4;

    var currentTick_486540351 = gameUtil.getTicks();
    console.log(("Current tick: "), (currentTick_486540351));
    var creeps_486540370 = getAllCreeps_1040187394();
    console.log(("found creeps: "), ((creeps_486540370).length));
    var flags_486540392 = getAllFlags_1040187396();
    console.log(("found flags: "), ((flags_486540392).length));
    Label1: do {
      var c_486540434 = null;
      var i_486540485 = 0;
      var L_486540486 = (creeps_486540370).length;
      Label2: do {
          Label3: while (true) {
          if (!(i_486540485 < L_486540486)) break Label3;
            c_486540434 = creeps_486540370[chckIndx(i_486540485, 0, (creeps_486540370).length - 1)];
            var closestFlag_486540439 = c_486540434.findClosestByPath(flags_486540392);
            if (!((closestFlag_486540439 == null))) {
            var res_486540444 = c_486540434.moveTo(closestFlag_486540439);
            Temporary4 = console.log(("move result: "), (res_486540444));
            }
            else {
            Temporary4 = console.log(("no flags found"));
            }
            
            Temporary4;
            i_486540485 = addInt(i_486540485, 1);
            if (!(((creeps_486540370).length == L_486540486))) {
            failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      } while (false);
    } while (false);

  
}
var creep1_486540488 = [null];
var creep2_486540489 = [null];
var flag1_486540490 = [null];
var flag2_486540491 = [null];

function getAllSpawns_1040187402() {
  var result_1040187403 = [];

      return gameUtil.getObjectsByPrototype(StructureSpawn);
  

  return result_1040187403;

}

function spawnCreep_1040187411(sArg_1040187412, bodyArg_1040187413) {
  var result_1040187414 = ({error: ({error: 0}), creep: null});

    var s = sArg_1040187412;
    var body = nimCopy(null, bodyArg_1040187413, NTI1040187411);
      const result = s.spawnCreep(body);
  if (result.error) {
    return {error: result.error};
  } else {
    return {creep: result};
  }
  

  return result_1040187414;

}

function spawnCreeps() {
      var Temporary1;
      var Temporary2;
    var Temporary3;
    var Temporary4;

    var currentTick_486540493 = gameUtil.getTicks();
    console.log(("Current tick: "), (currentTick_486540493));
    var creeps_486540512 = getAllCreeps_1040187394();
    console.log(("found creeps: "), ((creeps_486540512).length));
      if (!(creep1_486540488[0] == null)) Temporary1 = false; else {        Temporary1 = (0 < (creeps_486540512).length);      }    if (Temporary1) {
    creep1_486540488[0] = creeps_486540512[chckIndx(0, 0, (creeps_486540512).length - 1)];
    }
    
      if (!(creep2_486540489[0] == null)) Temporary2 = false; else {        Temporary2 = (1 < (creeps_486540512).length);      }    if (Temporary2) {
    creep2_486540489[0] = creeps_486540512[chckIndx(1, 0, (creeps_486540512).length - 1)];
    }
    
    var flags_486540552 = getAllFlags_1040187396();
    console.log(("found flags: "), ((flags_486540552).length));
    if ((flag1_486540490[0] == null)) {
    flag1_486540490[0] = flags_486540552[chckIndx(0, 0, (flags_486540552).length - 1)];
    }
    
    if ((flag2_486540491[0] == null)) {
    flag2_486540491[0] = flags_486540552[chckIndx(1, 0, (flags_486540552).length - 1)];
    }
    
    var spawns_486540580 = getAllSpawns_1040187402();
    console.log(("found spawns: "), ((spawns_486540580).length));
    if (((creep1_486540488[0] == null) || (creep2_486540489[0] == null))) {
    if ((0 < (spawns_486540580).length)) {
    var spawn_486540615 = spawns_486540580[chckIndx(0, 0, (spawns_486540580).length - 1)];
    var res_486540620 = spawnCreep_1040187411(spawn_486540615, ["work", "move"]);
    if ((res_486540620.creep == null)) {
    Temporary4 = console.log(("spawn creep error: "), (res_486540620));
    }
    else {
    Temporary4 = console.log(("spawn creep result: "), (res_486540620));
    }
    
    Temporary3 = Temporary4;
    }
    else {
    Temporary3 = console.log(("no spawns found"));
    }
    
    Temporary3;
    }
    
    if (!((creep1_486540488[0] == null))) {
    var res_486540674 = creep1_486540488[0].moveTo(flag1_486540490[0]);
    console.log(("move result: "), (res_486540674));
    }
    
    if (!((creep2_486540489[0] == null))) {
    var res_486540696 = creep2_486540489[0].moveTo(flag2_486540491[0]);
    console.log(("move result: "), (res_486540696));
    }
    

  
}

function getAllSources_1040187404() {
  var result_1040187405 = [];

      return gameUtil.getObjectsByPrototype(Source);
  

  return result_1040187405;

}

function harvestEnergy() {
    var currentTick_486540743 = gameUtil.getTicks();
    console.log(("Current tick: "), (currentTick_486540743));
    var creeps_486540762 = getAllCreeps_1040187394();
    console.log(("found creeps: "), ((creeps_486540762).length));
    var sources_486540784 = getAllSources_1040187404();
    console.log(("found sources: "), ((sources_486540784).length));
    var spawns_486540807 = getAllSpawns_1040187402();
    console.log(("found spawns: "), ((spawns_486540807).length));
    Label1: do {
      var c_486540832 = null;
      var i_486540900 = 0;
      var L_486540901 = (creeps_486540762).length;
      Label2: do {
          Label3: while (true) {
          if (!(i_486540900 < L_486540901)) break Label3;
            c_486540832 = creeps_486540762[chckIndx(i_486540900, 0, (creeps_486540762).length - 1)];
            if ((c_486540832.store.getCapacity() == c_486540832.store.getUsedCapacity())) {
            if ((0 < (spawns_486540807).length)) {
            var spawn_486540839 = spawns_486540807[chckIndx(0, 0, (spawns_486540807).length - 1)];
            if ((c_486540832.transfer(spawn_486540839, "energy") == -9)) {
            var _ = c_486540832.moveTo(spawn_486540839);
            }
            
            }
            else {
            console.log(("no spawns found"));
            }
            
            }
            else {
              if ((0 < (sources_486540784).length)) {
              var source_486540865 = c_486540832.findClosestByPath(sources_486540784);
              if ((c_486540832.harvest(source_486540865) == -9)) {
              var _ = c_486540832.moveTo(source_486540865);
              }
              
              }
              else {
              console.log(("no sources found"));
              }
              
            }
            
            i_486540900 = addInt(i_486540900, 1);
            if (!(((creeps_486540762).length == L_486540901))) {
            failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      } while (false);
    } while (false);

  
}
var constructionSite1_486540903 = [null];
var goBuild_486540904 = [false];

function getAllConstructionSites_1040187406() {
  var result_1040187407 = [];

      return gameUtil.getObjectsByPrototype(ConstructionSite);
  

  return result_1040187407;

}

function createStructureTower_1040187429(posArg_1040187430) {
  var result_1040187431 = ({error: ({error: 0}), constructionSite: null});

    var pos = posArg_1040187430;
      const result = gameUtil.createConstructionSite(pos, StructureTower);
  if (result.error) {
    return {error: result.error};
  } else {
    return {constructionSite: result};
  }
  

  return result_1040187431;

}

function towerConstruction() {
    var Temporary1;

    var currentTick_486540915 = gameUtil.getTicks();
    console.log(("Current tick: "), (currentTick_486540915));
    var creeps_486540934 = getAllCreeps_1040187394();
    console.log(("found creeps: "), ((creeps_486540934).length));
    var containers_486540956 = getAllContainers_1040187398();
    console.log(("found sources: "), ((containers_486540956).length));
    var spawns_486540978 = getAllSpawns_1040187402();
    console.log(("found spawns: "), ((spawns_486540978).length));
    var sites_486541000 = getAllConstructionSites_1040187406();
    console.log(("found construction sites: "), ((sites_486541000).length));
    if ((constructionSite1_486540903[0] == null)) {
    var res_486541026 = createStructureTower_1040187429({x: 50, y: 55});
    if (!((res_486541026.constructionSite == null))) {
    constructionSite1_486540903[0] = res_486541026.constructionSite;
    Temporary1 = console.log(("created construction site"));
    }
    else {
    Temporary1 = console.log(("createStructureTower error: "), (res_486541026.error));
    }
    
    Temporary1;
    }
    
    Label2: do {
      var c_486541062 = null;
      var i_486541220 = 0;
      var L_486541221 = (creeps_486540934).length;
      Label3: do {
          Label4: while (true) {
          if (!(i_486541220 < L_486541221)) break Label4;
            c_486541062 = creeps_486540934[chckIndx(i_486541220, 0, (creeps_486540934).length - 1)];
            console.log(("goBuild: "), (goBuild_486540904[0]));
            console.log(("constructionSite1: "), (constructionSite1_486540903[0]));
            if (goBuild_486540904[0]) {
            console.log(("gobuild!!!"));
            if ((c_486541062.store.getUsedCapacity() == 0)) {
            console.log(("no go build"));
            goBuild_486540904[0] = false;
            }
            else {
              console.log(("log1"));
              var res_486541132 = c_486541062.build(sites_486541000[chckIndx(0, 0, (sites_486541000).length - 1)]);
              console.log(("build result: "), (res_486541132));
              if (!((res_486541132 == 0))) {
              console.log(("log2"));
              var _ = c_486541062.moveTo(sites_486541000[chckIndx(0, 0, (sites_486541000).length - 1)]);
              }
              
            }
            
            }
            else {
              if ((c_486541062.store.getFreeCapacity() == 0)) {
              goBuild_486540904[0] = true;
              }
              else {
                if ((0 < (containers_486540956).length)) {
                var container_486541176 = c_486541062.findClosestByPath(containers_486540956);
                if ((c_486541062.withdraw(container_486541176, "energy") == -9)) {
                var _ = c_486541062.moveTo(container_486541176);
                }
                
                }
                else {
                console.log(("no sources found"));
                }
                
              }
              
            }
            
            i_486541220 = addInt(i_486541220, 1);
            if (!(((creeps_486540934).length == L_486541221))) {
            failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      } while (false);
    } while (false);

  
}

function finalTest() {
              var Temporary7;
              var Temporary14;
    var Temporary18;
    var Temporary19;

    var currentTick_486541224 = gameUtil.getTicks();
    console.log(("Current tick: "), (currentTick_486541224));
    var creeps_486541243 = getAllCreeps_1040187394();
    console.log(("found creeps: "), ((creeps_486541243).length));
    var spawns_486541265 = getAllSpawns_1040187402();
    console.log(("found spawns: "), ((spawns_486541265).length));
    var spawn_486541287 = spawns_486541265[chckIndx(0, 0, (spawns_486541265).length - 1)];
    var resultHEX60gensym354_486541292 = newSeq_486539512(0);
    Label1: do {
      var it_486541296 = null;
      var i_486541550 = 0;
      var L_486541551 = (creeps_486541243).length;
      Label2: do {
          Label3: while (true) {
          if (!(i_486541550 < L_486541551)) break Label3;
            it_486541296 = creeps_486541243[chckIndx(i_486541550, 0, (creeps_486541243).length - 1)];
            if ((it_486541296.my == false)) {
            resultHEX60gensym354_486541292.push(it_486541296);;
            }
            
            i_486541550 = addInt(i_486541550, 1);
            if (!(((creeps_486541243).length == L_486541551))) {
            failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      } while (false);
    } while (false);
    var enemyCreeps_486541301 = nimCopy(null, resultHEX60gensym354_486541292, NTI486539392);
    var resultHEX60gensym355_486541306 = newSeq_486539512(0);
    Label4: do {
      var it_486541310 = null;
      var i_486541558 = 0;
      var L_486541559 = (creeps_486541243).length;
      Label5: do {
          Label6: while (true) {
          if (!(i_486541558 < L_486541559)) break Label6;
            it_486541310 = creeps_486541243[chckIndx(i_486541558, 0, (creeps_486541243).length - 1)];
              if (!(it_486541310.my == true)) Temporary7 = false; else {                var resultHEX60gensym356_486541312 = false;
                Label8: do {
                  var it_486541316 = null;
                  var i_486541555 = 0;
                  var L_486541556 = (it_486541310.body).length;
                  Label9: do {
                      Label10: while (true) {
                      if (!(i_486541555 < L_486541556)) break Label10;
                        it_486541316 = it_486541310.body[chckIndx(i_486541555, 0, (it_486541310.body).length - 1)];
                        if ((it_486541316.type == "work")) {
                        resultHEX60gensym356_486541312 = true;
                        break Label8;
                        }
                        
                        i_486541555 = addInt(i_486541555, 1);
                        if (!(((it_486541310.body).length == L_486541556))) {
                        failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                        }
                        
                      }
                  } while (false);
                } while (false);
                Temporary7 = resultHEX60gensym356_486541312;              }            if (Temporary7) {
            resultHEX60gensym355_486541306.push(it_486541310);;
            }
            
            i_486541558 = addInt(i_486541558, 1);
            if (!(((creeps_486541243).length == L_486541559))) {
            failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      } while (false);
    } while (false);
    var workerCreeps_486541321 = nimCopy(null, resultHEX60gensym355_486541306, NTI486539392);
    var resultHEX60gensym357_486541326 = newSeq_486539512(0);
    Label11: do {
      var it_486541330 = null;
      var i_486541566 = 0;
      var L_486541567 = (creeps_486541243).length;
      Label12: do {
          Label13: while (true) {
          if (!(i_486541566 < L_486541567)) break Label13;
            it_486541330 = creeps_486541243[chckIndx(i_486541566, 0, (creeps_486541243).length - 1)];
              if (!(it_486541330.my == true)) Temporary14 = false; else {                var resultHEX60gensym358_486541332 = false;
                Label15: do {
                  var it_486541336 = null;
                  var i_486541563 = 0;
                  var L_486541564 = (it_486541330.body).length;
                  Label16: do {
                      Label17: while (true) {
                      if (!(i_486541563 < L_486541564)) break Label17;
                        it_486541336 = it_486541330.body[chckIndx(i_486541563, 0, (it_486541330.body).length - 1)];
                        if ((it_486541336.type == "attack")) {
                        resultHEX60gensym358_486541332 = true;
                        break Label15;
                        }
                        
                        i_486541563 = addInt(i_486541563, 1);
                        if (!(((it_486541330.body).length == L_486541564))) {
                        failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                        }
                        
                      }
                  } while (false);
                } while (false);
                Temporary14 = resultHEX60gensym358_486541332;              }            if (Temporary14) {
            resultHEX60gensym357_486541326.push(it_486541330);;
            }
            
            i_486541566 = addInt(i_486541566, 1);
            if (!(((creeps_486541243).length == L_486541567))) {
            failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      } while (false);
    } while (false);
    var combatCreeps_486541341 = nimCopy(null, resultHEX60gensym357_486541326, NTI486539392);
    console.log(("store capacity"), (spawn_486541287.store.getUsedCapacity()));
    if (((workerCreeps_486541321).length < 2)) {
    var res_486541367 = spawnCreep_1040187411(spawn_486541287, ["work", "move", "carry"]);
    if ((res_486541367.creep == null)) {
    Temporary18 = console.log(("spawn creep error: "), (res_486541367));
    }
    else {
    Temporary18 = console.log(("spawn creep result: "), (res_486541367));
    }
    
    Temporary18;
    }
    
    if ((2 <= (workerCreeps_486541321).length)) {
    var res_486541417 = spawnCreep_1040187411(spawn_486541287, ["move", "attack"]);
    if ((res_486541417.creep == null)) {
    Temporary19 = console.log(("spawn creep error: "), (res_486541417));
    }
    else {
    Temporary19 = console.log(("spawn creep result: "), (res_486541417));
    }
    
    Temporary19;
    }
    
    Label20: do {
      var worker_486541460 = null;
      var i_486541570 = 0;
      var L_486541571 = (workerCreeps_486541321).length;
      Label21: do {
          Label22: while (true) {
          if (!(i_486541570 < L_486541571)) break Label22;
            worker_486541460 = workerCreeps_486541321[chckIndx(i_486541570, 0, (workerCreeps_486541321).length - 1)];
            if ((0 < worker_486541460.store.getFreeCapacity())) {
            var sources_486541461 = getAllSources_1040187404();
            if ((0 < (sources_486541461).length)) {
            var source_486541472 = worker_486541460.findClosestByPath(sources_486541461);
            if ((worker_486541460.harvest(source_486541472) == -9)) {
            var _ = worker_486541460.moveTo(source_486541472);
            }
            
            }
            else {
            console.log(("no sources found"));
            }
            
            }
            else {
              if ((0 < (spawns_486541265).length)) {
              var spawn_486541494 = spawns_486541265[chckIndx(0, 0, (spawns_486541265).length - 1)];
              if ((worker_486541460.transfer(spawn_486541494, "energy") == -9)) {
              var _ = worker_486541460.moveTo(spawn_486541494);
              }
              
              }
              else {
              console.log(("no spawns found"));
              }
              
            }
            
            i_486541570 = addInt(i_486541570, 1);
            if (!(((workerCreeps_486541321).length == L_486541571))) {
            failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      } while (false);
    } while (false);
    Label23: do {
      var combat_486541513 = null;
      var i_486541574 = 0;
      var L_486541575 = (combatCreeps_486541341).length;
      Label24: do {
          Label25: while (true) {
          if (!(i_486541574 < L_486541575)) break Label25;
            combat_486541513 = combatCreeps_486541341[chckIndx(i_486541574, 0, (combatCreeps_486541341).length - 1)];
            if ((0 < (enemyCreeps_486541301).length)) {
            var enemy_486541524 = combat_486541513.findClosestByPath(enemyCreeps_486541301);
            if ((combat_486541513.attack(enemy_486541524) == -9)) {
            var _ = combat_486541513.moveTo(enemy_486541524);
            }
            
            }
            else {
            console.log(("no enemy creeps found"));
            }
            
            i_486541574 = addInt(i_486541574, 1);
            if (!(((combatCreeps_486541341).length == L_486541575))) {
            failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      } while (false);
    } while (false);

  
}
export const loop = finalTest;

